### ISSUE TITLE
Day view calories not lining up

### ISSUE THREAD

**Issue by jdaudier** [loicginoux/joanne_project#29]
The day view calories are not matching the images.  Perhaps when the images are moved the calories are not.  See my account July 26 as an example.

http://screencast.com/t/xLUF06KO

**Comment by loicginoux** [comment]
they are aligned but the last 2 images are missing, I will check what's going on with this images, I'll comment later when I find the issue

**Comment by loicginoux** [comment]
ok I corrected the issue locally, I will push that at the end of the day when I finished working for the day. The problem was that these files had the extension "jpeg" (all the others had "jpg") and when trying to dysplaing the image it was looking for a file with extension "jpg" and couldn't find it.
Now all files will be transformed in a "jpg" image

**Comment by jdaudier** [comment]
I still see a misalignment on Thur July 26.  http://www.diigo.com/item/image/2yj1s/rweu

**Comment by loicginoux** [comment]
This is because I fix the problem for new images but the old ones haven't been processed by the file server. From now on, this issue will be fixed. For old ones I would have to go on s3 and check for all images if the original is "jpeg" and change the  generated one to "jpg". 
If the site was fully in production, I would have to do it, but because we are still in development and we don't have that many users, I will leave the bug for old images.
Is it ok if I do it like that or do you prefer me to fix it for old ones as well? 
Just to show you I will fix the extension for the 3 images missing on thursday 26.
